POST http://localhost:9000/clients HTTP/1.1
Content-Type: application/json

{
    "name": "Jane Doe",
    "email": "jane@j.com"
}

###

POST http://localhost:9000/accounts HTTP/1.1
Content-Type: application/json

{
    "client_id": "3854295f-439d-46d2-a00b-849dd444e0dc"
}

###

POST http://localhost:9000/transactions HTTP/1.1
Content-Type: application/json

{
    "account_id_from": "1be404a2-e2dd-4572-bea0-e5558ea8c659",
    "account_id_to": "94c17bad-66fe-4f6b-bafa-bf113d0c678f",
    "amount": 500
}