POST http://localhost:8080/clients HTTP/1.1
Content-Type: application/json

{
    "name": "Samuca",
    "email": "samuca@s.com"
}

###

POST http://localhost:8080/accounts HTTP/1.1
Content-Type: application/json

{
    "client_id": "c995e35d-1927-4cbb-b873-8e9dc946f062"
}

###

POST http://localhost:8080/transactions HTTP/1.1
Content-Type: application/json

{
    "account_id_from": "7dfe0fa9-d168-4329-a9ba-ca1b7052fac3",
    "account_id_to": "c6aee752-9977-46c3-9fa0-29e14f85f73f",
    "amount": 5
}